project:
  type: book
  output-dir: docs

book:
  title: "NIVA Reference Rivers"
  date: "August 9, 2022"
  chapters:
    - index.qmd
    - book_spatial.qmd
    - book_climate.qmd
    - book_waterchem.qmd
    - book_multivariate.qmd
    - book_fluxes.qmd
    - book_drought.qmd

format:
  html:
    theme: cosmo
    code-link: true
