project:
  type: book
  output-dir: docs

book:
  title: "Reference Rivers"
  author: "Maeve McGovern"
  date: "August 9, 2022"
  cover-image: cover.png
  chapters:
    - book_intro.qmd
    - book_spatial.qmd
    - book_waterchem.qmd
    - book_multivariate.qmd
    - book_fluxes.qmd

format:
  html:
    theme: cosmo
    code-link: true
