---
title: "RefElv_Fluxes"
format: html
editor: visual
---

```{r}
knitr::opts_chunk$set(echo=F, message=F, warning=F)

# Load libraries
library(tidyverse)
library(broom)
library(fs)
library(caret)
#library(sf)
library(terra)
library(units)
#library(raster)
#library(rgeos)
#library(tmap)
library(lubridate)
library(jpeg)
library(pdftools)
#library(arrow)
library(zoo)
library(patchwork)
library(ggh4x)
library(Hmisc)
library(ggstance)

#library(kmlShape)
#library(ggspatial)
#library("rnaturalearth")
#library("rnaturalearthdata")
library(RColorBrewer)

#library(dichromat)
#colorschemes
```

# files for juptyerhub

```{r}
### For matching to Python workflow
Water_Chem_select <- read_csv("Clean_Data/Water_Chem_select.csv")
DOC_data <- Water_Chem_select %>% 
  ungroup() %>% 
  filter(grepl("2018", Date)) %>% 
  filter(site_id == "F_212_1729_Lah") %>% 
  dplyr::select(date = Date, DOC_mg_L) 
  
write_csv(DOC_data, "Clean_Data/Intermediate/DOC_data.csv")

Drought_Daily3 <- read_csv("Clean_Data/Intermediate/Drought_Data_daily2.csv") %>% 
    filter(grepl("2018", date)) %>% 
    filter(site_id == "F_212_1729_Lah") %>% 
    dplyr::select(date, Q) 

write_csv(Drought_Daily3, "Clean_Data/Intermediate/Drought_Daily3.csv")

#interp_data <- full_join(Drought_Daily, DOC_data) %>% 
 #   filter(grepl("2018", date)) %>% 
  #filter(site_id == "F_212_1729_Lah")
#
# NivaPy includes a stats module that implements several robust, non-parametric trend tests such as Mann-Kendall and Sen's slope. These are simple, but well suited to the characteristics of typical environmental datasets. In the code below, we test for a trend in the mean annual TOC concentration at Langtjern.on annual averages

# NivaPy's stats module includes an estimate_fluxes function, which provides basic tools for calculating riverine fluxes/loads (this functionality will be expanded over time). For a description of what's currently available, use the help system, as described above:
  
# We will compare the results for annual fluxes from three different flux estimation procedures for TOC at Langtjern. First, however, we need to rename some columns in our data: as described in the help file above, the estimate_fluxes function expects the discharge column to be named flow_m3/s (not Q) and the chemistry data to be named e.g. TOC_mg/l (not TOC_mgpl). This can easily be changed:

# We now loop over the three methods of estimating fluxes and join the results into a single dataframe (using similar techniques to those described above). This code is a little more complicated than anything else in this notebook, but it's mostly a matter of combining ideas introduced above with basic Python syntax for looping and merging data.
  
# linear_interpolation
# simple_means
# log_log_linear_regression
# ospar_annual
```

# Linear interpolation and flux calculation

```{r}
Drought_Daily <- read_csv("Clean_Data/Intermediate/Drought_Data_daily.csv") %>%
  separate(datetime, c("date", "Time"), sep = " ") %>% 
  filter(par =="Q") %>%  # unit = L_day
  dplyr::select(c(site_id, par, date, value_mean)) %>% 
  distinct() %>% 
  pivot_wider(names_from ="par", values_from = "value_mean") %>% 
  dplyr::select(site_id, date, Q) %>% 
  mutate(date = ymd(date)) 

write_csv(Drought_Daily, "Clean_Data/Intermediate/Drought_Data_daily2.csv")
Water_Chem_select <- read_csv("Clean_Data/Water_Chem_select.csv")
Drought_Daily <- read_csv("Clean_Data/Intermediate/Drought_Data_daily2.csv")

Water_data <- Water_Chem_select %>% 
  ungroup() %>% 
  dplyr::select(site_id, date=Date, Color_mg_L = Water_Color_mgPt_l, Ca_mg_L, Fe_ug_L, DOC_mg_L, TotP_ug_L, TotN_ug_L, NO3_ug_L) 

interp_data <- full_join(Drought_Daily, Water_data) %>% 
  drop_na(Q)

# Daily concentrations (linear interpolation)

# 2017
df_2017 <- interp_data %>%
  filter(grepl("2017",date)) %>% 
  mutate(date = ymd(date)) %>%
  mutate(month = month(date)) %>%
  mutate(year = year(date)) %>% 
  pivot_longer(cols = -c(site_id, date, Q, year, month), values_to = "concentrations", names_to = "variable") %>%
  group_by(site_id, variable) %>% 
  mutate(concentrations = na.approx(concentrations, x = date, rule = 2, na.rm = FALSE)) %>% 
  drop_na(concentrations) %>% 
  group_by(site_id, variable, date) %>% 
  mutate(flux = concentrations * Q) %>%  
  mutate(flux = ifelse(grepl("mg_L", variable), flux/1000000000, flux)) %>% #mg/day to tonnes/day
  mutate(flux = ifelse(grepl("ug_L", variable), flux/1000000000000, flux)) #ug/day to tonnes/day

monthly_flux_2017 <- df_2017 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, flux, year, month)) %>% 
  group_by(site_id, variable, year, month) %>% 
  summarise(monthly_flux = sum(flux, na.rm = TRUE))

annual_flux_2017 <- df_2017 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, year, flux)) %>% 
  group_by(site_id, variable, year) %>% 
  summarise(annual_flux = sum(flux, na.rm = TRUE))


# 2018
df_2018 <- interp_data %>%
  filter(grepl("2018",date)) %>% 
  mutate(date = ymd(date)) %>%
  mutate(month = month(date)) %>%
  mutate(year = year(date)) %>% 
  pivot_longer(cols = -c(site_id, date, Q, year, month), values_to = "concentrations", names_to = "variable") %>%
  group_by(site_id, variable) %>% 
  mutate(concentrations = na.approx(concentrations, x = date, rule = 2, na.rm = FALSE)) %>% 
  drop_na(concentrations) %>% 
  group_by(site_id, variable, date) %>% 
  mutate(flux = concentrations * Q) %>% 
  mutate(flux = ifelse(grepl("mg_L", variable), flux/1000000000, flux)) %>% #mg/day to tonnes/day
  mutate(flux = ifelse(grepl("ug_L", variable), flux/1000000000000, flux)) #ug/day to tonnes/day
monthly_flux_2018 <- df_2018 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, flux, year, month)) %>% 
  group_by(site_id, variable, year, month) %>% 
  summarise(monthly_flux = sum(flux, na.rm = TRUE))

annual_flux_2018 <- df_2018 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, year, flux)) %>% 
  group_by(site_id, variable, year) %>% 
  summarise(annual_flux = sum(flux, na.rm = TRUE))


# 2019
df_2019 <- interp_data %>%
  filter(grepl("2019",date)) %>% 
  mutate(date = ymd(date)) %>%
  mutate(month = month(date)) %>%
  mutate(year = year(date)) %>% 
  pivot_longer(cols = -c(site_id, date, Q, year, month), values_to = "concentrations", names_to = "variable") %>%
  group_by(site_id, variable) %>% 
  mutate(concentrations = na.approx(concentrations, x = date, rule = 2, na.rm = FALSE)) %>% 
  drop_na(concentrations) %>% 
  group_by(site_id, variable, date) %>% 
  mutate(flux = concentrations * Q) %>% 
  mutate(flux = ifelse(grepl("mg_L", variable), flux/1000000000, flux)) %>% #mg/day to tonnes/day
  mutate(flux = ifelse(grepl("ug_L", variable), flux/1000000000000, flux)) #ug/day to tonnes/day
monthly_flux_2019 <- df_2019 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, flux, year, month)) %>% 
  group_by(site_id, variable, year, month) %>% 
  summarise(monthly_flux = sum(flux, na.rm = TRUE))

annual_flux_2019 <- df_2019 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, year, flux)) %>% 
  group_by(site_id, variable, year) %>% 
  summarise(annual_flux = sum(flux, na.rm = TRUE))

# 2020
df_2020 <- interp_data %>%
  filter(grepl("2020",date)) %>% 
  mutate(date = ymd(date)) %>%
  mutate(month = month(date)) %>%
  mutate(year = year(date)) %>% 
  pivot_longer(cols = -c(site_id, date, Q, year, month), values_to = "concentrations", names_to = "variable") %>%
  group_by(site_id, variable) %>% 
  mutate(concentrations = na.approx(concentrations, x = date, rule = 2, na.rm = FALSE)) %>% 
  drop_na(concentrations) %>% 
  group_by(site_id, variable, date) %>% 
  mutate(flux = concentrations*Q) %>% 
  mutate(flux = ifelse(grepl("mg_L", variable), flux/1000000000, flux)) %>% #mg/day to tonnes/day
  mutate(flux = ifelse(grepl("ug_L", variable), flux/1000000000000, flux)) #ug/day to tonnes/day
monthly_flux_2020 <- df_2020 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, flux, year, month)) %>% 
  group_by(site_id, variable, year, month) %>% 
  summarise(monthly_flux = sum(flux, na.rm = TRUE))

annual_flux_2020 <- df_2020 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, year, flux)) %>% 
  group_by(site_id, variable, year) %>% 
  summarise(annual_flux = sum(flux, na.rm = TRUE))

  
# 2021
df_2021 <- interp_data %>%
  filter(grepl("2021",date)) %>% 
  mutate(date = ymd(date)) %>%
  mutate(month = month(date)) %>%
  mutate(year = year(date)) %>% 
  pivot_longer(cols = -c(site_id, date, Q, year, month), values_to = "concentrations", names_to = "variable") %>%
  group_by(site_id, variable) %>% 
  mutate(concentrations = na.approx(concentrations, x = date, rule = 2, na.rm = FALSE)) %>% 
  drop_na(concentrations) %>% 
  group_by(site_id, variable, date) %>% 
  mutate(flux = concentrations * Q) %>% 
  mutate(flux = ifelse(grepl("mg_L", variable), flux/1000000000, flux)) %>% #mg/day to tonnes/day
  mutate(flux = ifelse(grepl("ug_L", variable), flux/1000000000000, flux)) #ug/day to tonnes/day
monthly_flux_2021 <- df_2021 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, flux, year, month)) %>% 
  group_by(site_id, variable, year, month) %>% 
  summarise(monthly_flux = sum(flux, na.rm = TRUE))

annual_flux_2021 <- df_2021 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, year, flux)) %>% 
  group_by(site_id, variable, year) %>% 
  summarise(annual_flux = sum(flux, na.rm = TRUE))


# 2022
df_2022 <- interp_data %>%
  filter(grepl("2022",date)) %>% 
  mutate(date = ymd(date)) %>%
  mutate(month = month(date)) %>%
  mutate(year = year(date)) %>% 
  pivot_longer(cols = -c(site_id, date, Q, year, month), values_to = "concentrations", names_to = "variable") %>%
  group_by(site_id, variable) %>% 
  mutate(concentrations = na.approx(concentrations, x = date, rule = 2, na.rm = FALSE)) %>% 
  drop_na(concentrations) %>% 
  group_by(site_id, variable, date) %>% 
  mutate(flux = concentrations * Q) %>% 
  mutate(flux = ifelse(grepl("mg_L", variable), flux/1000000000, flux)) %>% #mg/day to tonnes/day
  mutate(flux = ifelse(grepl("ug_L", variable), flux/1000000000000, flux)) #ug/day to tonnes/day

monthly_flux_2022 <- df_2022 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, flux, year, month)) %>% 
  group_by(site_id, variable, year, month) %>% 
  summarise(monthly_flux = sum(flux, na.rm = TRUE))

annual_flux_2022 <- df_2022 %>% 
  ungroup() %>% 
  dplyr::select(c(site_id, variable, year, flux)) %>% 
  group_by(site_id, variable, year) %>% 
  summarise(annual_flux = sum(flux, na.rm = TRUE))

# joining
daily_flux_all <- rbind(df_2017, df_2018, df_2019, df_2020, df_2021, df_2022) %>%  distinct()
  
annual_flux_all <- rbind(annual_flux_2017, annual_flux_2018, annual_flux_2019, annual_flux_2020, annual_flux_2021, annual_flux_2022) %>%  distinct()

monthly_flux_all <- rbind(monthly_flux_2017, monthly_flux_2018, monthly_flux_2019, monthly_flux_2020, monthly_flux_2021, monthly_flux_2022) %>%  distinct() %>% 
  pivot_wider(names_from = "variable", values_from = "monthly_flux") %>% 
  group_by(site_id, year, month) %>% 
  mutate(N_P = NO3_ug_L/TotP_ug_L) %>% 
  pivot_longer(cols = -c(site_id, month, year), values_to = "monthly_flux", names_to = "variable")

write_csv(daily_flux_all, "Clean_Data/daily_flux_all.csv")
write_csv(monthly_flux_all, "Clean_Data/monthly_flux_all.csv")
write_csv(annual_flux_all, "Clean_Data/annual_flux_all.csv")
```

# Annual Flux

```{r}
# Annual Flux
annual_flux_all <- read_csv("Clean_Data/annual_flux_all.csv") %>% 
    mutate(variable = str_replace_all(variable, "_ug_L", "")) %>%
    mutate(variable = str_replace_all(variable, "_mg_L", ""))

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

Data76 <- full_join(annual_flux_all, Station_Info) %>% drop_na() %>% 
  filter(group %in% c("'18/'20")) %>% 
  filter(year %in% c("2018", "2020")) %>% 
  mutate(year = as.character(year)) %>% 
  filter(okoregion %in% c("Finnmark", "Ostlandet", "Vest")) %>% 
  filter(variable != "Color")

Data76$variable <- factor(Data76$variable, 
    levels = c("DOC", "Fe", "TotP", "TotN", "NO3", "Ca"),
    labels = c("DOC", "Fe",  "TotP", "TotN", "NO3", "Ca"))

Data76$okoregion <- factor(Data76$okoregion, 
    levels = c("Finnmark", "Ostlandet", "Vest"),
    labels = c("Finnmark", "Østlandet", "Vestlandet"))
  
  
options(scipen = 99999999)
Plot <- Data76 %>% 
  ggplot(aes(x = okoregion, y = annual_flux, fill = year)) +
  geom_boxplot(outlier.shape =  NA,alpha = 0.7, width = 0.5) +
    scale_fill_manual(values=c("#FFCC66", "#264EFF")) +
  scale_y_log10() + 
  facet_wrap(~variable, scales = "free", ncol = 3) +
  theme_bw() +
  xlab(NULL) + ylab("Annual Flux (tonnes)") +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) 

ggsave("Figures/Annual_Flux_18_20.pdf", Plot, width = 6, height = 4, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Annual_Flux_18_20.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Annual_Flux_18_20.jpeg")


options(scipen = 99999999)
Plot <- full_join(annual_flux_all, Station_Info) %>% drop_na() %>% 
  filter(variable != "Color") %>% 
  filter(group %in% c("'19/'21")) %>% 
  filter(year %in% c("2019", "2021")) %>% 
  mutate(year = as.character(year)) %>% 
  ggplot(aes(x = okoregion, y = annual_flux, fill = year)) +
  geom_boxplot(outlier.shape =  NA, alpha = 0.7, width = 0.5) +
  scale_fill_manual(values=c("#3399FF", "#FF8000")) +
  scale_y_log10() + 
  facet_wrap(~variable, scales = "free", ncol = 3) +
  theme_bw() +
  xlab(NULL) + ylab("Annual Flux (tonnes)") +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) 

ggsave("Figures/Annual_Flux_19_21.pdf", Plot, width = 6, height = 4, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Annual_Flux_19_21.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Annual_Flux_19_21.jpeg")


options(scipen = 99999999)
Plot <- full_join(annual_flux_all, Station_Info) %>% drop_na() %>% 
  filter(group %in% c("'18/'19/'20/'21")) %>% 
  filter(year %in% c("2018", "2019", "2020", "2021")) %>% 
  mutate(year = as.character(year)) %>% 
  ggplot(aes(x = okoregion, y = annual_flux, fill = year)) +
  geom_boxplot(outlier.shape =  NA, alpha = 0.7, width = 0.5) +
  scale_fill_manual(values=c("#FFCC66","#3399FF","#264EFF", "#FF8000")) +
  scale_y_log10() + 
  facet_wrap(~variable, scales = "free", ncol = 3) +
  theme_bw() +
  xlab(NULL) + ylab("Annual Flux (tonnes)") +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) 

ggsave("Figures/Annual_Flux_All4.pdf", Plot, width = 6, height = 4, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Annual_Flux_All4.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Annual_Flux_All4.jpeg")
```

```{r}
# Annual Flux
annual_flux_all <- read_csv("Clean_Data/annual_flux_all.csv") %>% 
    mutate(variable = str_replace_all(variable, "_ug_L", "")) %>%
    mutate(variable = str_replace_all(variable, "_mg_L", ""))

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

options(scipen = 99999999)
Plot <- full_join(annual_flux_all, Station_Info) %>% drop_na() %>% 
  filter(group %in% c("'19/'21")) %>% 
  filter(year %in% c("2019", "2021")) %>% 
  mutate(year = as.character(year)) %>% 
  ggplot(aes(x = okoregion, y = annual_flux, fill = year)) +
  geom_boxplot(outlier.shape =  NA,alpha = 0.7, width = 0.5) +
  scale_fill_manual(values=c("#3399FF", "#FF8000")) +
  scale_y_log10() + 
  facet_wrap(~variable, scales = "free", ncol = 3) +
  theme_bw() +
  xlab(NULL) + ylab("Annual Flux (tonnes)") +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) 

ggsave("Figures/Annual_Flux_19_21_bda.pdf", Plot, width = 6, height = 4, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Annual_Flux_19_21_bda.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Annual_Flux_19_21_bda.jpeg")

options(scipen = 99999999)
Plot <- full_join(annual_flux_all, Station_Info) %>% drop_na() %>% 
  filter(group %in% c("'18/'20")) %>% 
  filter(year %in% c("2018", "2020")) %>% 
  mutate(year = as.character(year)) %>% 
  ggplot(aes(x = okoregion, y = annual_flux, fill = year)) +
  geom_boxplot(outlier.shape =  NA, alpha = 0.7, width = 0.5) +
  scale_fill_manual(values=c("#FFCC66", "#264EFF")) +
  scale_y_log10() + 
  facet_wrap(~variable, scales = "free", ncol = 3) +
  theme_bw() +
  xlab(NULL) + ylab("Annual Flux (tonnes)") +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) 

ggsave("Figures/Annual_Flux_18_20_bda.pdf", Plot, width = 6, height = 4, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Annual_Flux_18_20_bda.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Annual_Flux_18_20_bda.jpeg")


options(scipen = 99999999)
Plot <- full_join(annual_flux_all, Station_Info) %>% drop_na() %>% 
  filter(group %in% c("'18/'19/'20/'21")) %>% 
  filter(year %in% c("2018", "2019", "2020", "2021")) %>% 
  mutate(year = as.character(year)) %>% 
  ggplot(aes(x = okoregion, y = annual_flux, fill = year)) +
  geom_boxplot(outlier.shape =  NA, alpha = 0.7, width = 0.5) +
  scale_fill_manual(values=c("#FFCC66","#3399FF","#264EFF", "#FF8000")) +
  scale_y_log10() + 
  facet_wrap(~variable, scales = "free", ncol = 3) +
  theme_bw() +
  xlab(NULL) + ylab("Annual Flux (tonnes)") +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) 

ggsave("Figures/Annual_Flux_All4_bda.pdf", Plot, width = 6, height = 4, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Annual_Flux_All4_bda.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Annual_Flux_All4_bda.jpeg")
```

# Monthly Flux: compare 2018 to 2020

```{r}

# Monthly Flux
monthly_flux_all <- read_csv("Clean_Data/monthly_flux_all.csv") %>% 
    mutate(variable = str_replace_all(variable, "_ug_L", "")) %>%
    mutate(variable = str_replace_all(variable, "_mg_L", "")) %>% 
    mutate(month = month(month, label = TRUE))

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

Climate <- read_csv("Clean_Data/Intermediate/Climate_processed.csv") %>% 
  pivot_longer(cols = -c(site_id, Date), names_to = "par", values_to = "monthly_mean") %>% 
  filter(grepl("rr", par)) %>% 
  mutate(year = year(Date),month = month(Date, label = TRUE), day = day(Date)) %>%
  distinct() %>% 
  mutate(sum_rr_mm = monthly_mean)

Station_Info3 <- full_join(Climate, monthly_flux_all)
Station_Info2 <- full_join(Station_Info3, Station_Info)

# 2018/2020
data45 <- Station_Info2 %>% drop_na() %>% 
  filter(group %in% c("'18/'20")) %>% 
  filter(year %in% c("2018", "2020")) %>% 
  filter(okoregion %in% c("Finnmark", "Ostlandet", "Vest")) %>% 
  mutate(year = as.character(year)) %>% 
  dplyr::select(-c(day, Date)) %>% distinct()

library(rstatix)
T_testR <- data45 %>%
  dplyr::select(site_id, okoregion, month, variable, monthly_flux, year) %>% 
  mutate(monthly_flux = log10(monthly_flux)) %>% 
  ungroup() %>% distinct() %>% dplyr::select(-site_id) %>% 
  unite("ID", okoregion, month, variable, sep = "-", remove = TRUE) %>% 
  nest(data = -c(ID)) %>%  
  mutate(t_test = map(data, ~tidy(pairwise.t.test(.x$monthly_flux ,.x$year, paired = TRUE, p.adjust.method="bonferroni")))) %>% 
  dplyr::select(-c(data)) %>% 
  unnest(t_test) %>% 
  mutate(p_value = round(p.value, 4)) %>% 
  dplyr::select(c(ID, p_value)) %>% 
  filter(p_value < 0.05) %>% 
  mutate(sign = "*") %>% 
  separate(ID, c("okoregion", "month", "variable"), sep = "-")

data45$variable_f <- factor(data45$variable,
                        levels = c("DOC", "Fe", "Color", "TotP", "TotN", "NO3", "N_P", "Ca"),
                        labels = c("DOC", "Fe", "Color", "TotP", "TotN", bquote('NO'[3]), bquote('NO'[3]~':TotP'), "Ca"))

T_testR$variable_f <- factor(T_testR$variable,
                        levels = c("DOC", "Fe", "Color", "TotP", "TotN", "NO3", "N_P", "Ca"),
                        labels = c("DOC", "Fe", "Color", "TotP", "TotN", bquote('NO'[3]), bquote('NO'[3]~':TotP'), "Ca"))


T_testR$okoregion <- factor(T_testR$okoregion,
                            levels = c("Finnmark", "Ostlandet", "Vest"),
                            labels = c("Finnmark", "Østlandet", "Vestlandet"))

data45$okoregion <- factor(data45$okoregion,
                            levels = c("Finnmark", "Ostlandet", "Vest"),
                            labels = c("Finnmark", "Østlandet", "Vestlandet"))

options(scipen = 99999999)
Plot <- ggplot() +
  geom_boxplot(data = data45, aes(x = month, y = monthly_flux, fill = year, color = year), outlier.shape =  NA,alpha = 0.7, width = 0.5) +
  scale_fill_manual(values=c("#FFCC66", "#264EFF")) +
  scale_color_manual(values=c("#FF8000", "#264EFF")) +
  scale_y_log10(name = "Monthly Flux (tonnes)") + 
  facet_grid(variable_f~okoregion, labeller = label_parsed) +
  theme_bw() +
  xlab(NULL) + ylab("Monthly Flux (tonnes)") +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) +
  geom_text(data = T_testR, aes(y = 1000, x = month, label = sign), size = 6, color = "black") 


ggsave("Figures/monthly_Flux_18_20_bda.pdf", Plot, width = 9, height = 10, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/monthly_Flux_18_20_bda.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/monthly_Flux_18_20_bda.jpeg")

# 2018/2020
tests <- data45 %>% 
  dplyr::select(c(site_id, variable, month,  monthly_flux, year, okoregion)) %>% distinct() %>% 
  group_by(variable, okoregion, month, year) %>% 
  summarise(monthly_flux_mean = mean(monthly_flux)) %>% 
  filter(variable == "TotP") %>% 
  filter(month %in% c("Jun", "Jul")) %>% 
  pivot_wider(names_from = "year", values_from = "monthly_flux_mean") %>% 
  mutate(factor = `2020`/`2018`) %>% 
  group_by(variable) %>% 
  summarise(factor_mean = mean(factor))

  #mutate(percent_change = ((`2020`-`2018`)/`2018`)*100) %>% 
 # group_by(variable) %>% 
 # summarise(percent_change_mean = mean(percent_change))


```



```{r}
# 2019/2021
data45 <- Station_Info2 %>% 
  ungroup() %>% 
  filter(group %in% c("'19/'21")) %>% 
  filter(year %in% c("2019","2021")) %>% 
  mutate(year = as.character(year)) %>% 
  pivot_wider(names_from = "variable", values_from = "monthly_flux") %>% 
  mutate(Date = ymd(Date), year = year(Date), month = month(Date, label = TRUE)) %>% 
  select(-c(day, Date, par, monthly_mean, sum_rr_mm, rapportnavn, group)) %>% 
  pivot_longer(cols = -c(site_id, okoregion, month, year), names_to = "variable", values_to = "monthly_flux") %>% 
  drop_na(variable) %>% distinct() %>% 
  pivot_wider(names_from = "variable", values_from = "monthly_flux") %>% 
  select(-"NA") %>% 
  pivot_longer(cols = -c(site_id, okoregion, month, year), names_to = "variable", values_to = "monthly_flux") 

data45$variable <- factor(data45$variable,
                        levels = c("DOC", "Fe", "Ca", "NO3", "TotN", "TotP", "N_P"),
                        labels = c("DOC", "Fe", "Ca", "NO3","TotN", "TotP","NO3:TP"))

T_testR <- data45 %>%
  dplyr::select(site_id, okoregion, month, variable, monthly_flux, year) %>% 
  mutate(monthly_flux = log10(monthly_flux)) %>% 
  ungroup() %>% distinct() %>% dplyr::select(-site_id) %>% 
  unite("ID", okoregion, month, variable, sep = "_", remove = TRUE) %>% 
  nest(data = -c(ID)) %>%  
  mutate(t_test = map(data, ~tidy(t.test(.x$monthly_flux, .x$year, paired = T)))) %>% 
  dplyr::select(-c(data)) %>% 
  unnest(t_test) %>% 
  mutate(p_value = round(p.value, 4)) %>% 
  dplyr::select(c(ID, p_value)) %>% 
  filter(p_value < 0.05) %>% 
  mutate(sign = "*") %>% 
  separate(ID, c("okoregion", "month", "variable"), sep = "_")

options(scipen = 99999999)
Plot <-   ggplot() +
  geom_boxplot(data = data45, aes(x = month, y = monthly_flux, fill = year, color = year), outlier.shape =  NA,alpha = 0.7, width = 0.5) +
  scale_color_manual(values=c("#3399FF", "#FF8000")) +
  scale_fill_manual(values=c("#3399FF", "#FF8000")) +
   facet_grid(variable~okoregion) +
  scale_y_log10(name = "Monthly Flux (tonnes)") + 
  theme_bw() +
  xlab(NULL) + 
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) +
  geom_text(data = T_testR, aes(y = 800, x = month, label = sign), size = 6, color = "black") 

ggsave("Figures/monthly_Flux_19_21_bda.pdf", Plot, width = 9, height = 10, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/monthly_Flux_19_21_bda.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/monthly_Flux_19_21_bda.jpeg")




# All 4

data45 <- Station_Info2 %>% drop_na() %>% 
  filter(group %in% c("'18/'19/'20/'21")) %>% 
  filter(year %in% c("2018", "2019", "2020", "2021")) %>% 
  mutate(year = as.character(year))

data45$variable <- factor(data45$variable,
                        levels = c("DOC", "Fe", "Ca", "NO3", "TotN", "TotP", "N_P"),
                        labels = c("DOC", "Fe", "Ca", "NO3","TotN", "TotP","NO3:TP"))

T_testR <- data45 %>%
  dplyr::select(site_id, okoregion, month, variable, monthly_flux, year) %>% 
  mutate(monthly_flux = log10(monthly_flux)) %>% 
  ungroup() %>% distinct() %>% dplyr::select(-site_id) %>% 
  unite("ID", okoregion, month, variable, sep = "_", remove = TRUE) %>% 
  nest(data = -c(ID)) %>%  
  mutate(t_test = map(data, ~tidy(t.test(.x$monthly_flux ~.x$year)))) %>% 
  dplyr::select(-c(data)) %>% 
  unnest(t_test) %>% 
  mutate(p_value = round(p.value, 4)) %>% 
  dplyr::select(c(ID, p_value)) %>% 
  filter(p_value < 0.05) %>% 
  mutate(sign = "*") %>% 
  separate(ID, c("okoregion", "month", "variable"), sep = "_")


options(scipen = 99999999)
Plot <- ggplot() +
  geom_boxplot(data = data45, aes(x = month, y = monthly_flux, fill = year), outlier.shape =  NA,alpha = 0.7, width = 0.5) +
  scale_fill_manual(values=c("#FFCC66","#3399FF","#264EFF", "#FF8000")) +
  scale_y_log10(name = "Monthly Flux (tonnes)") + # Features of the first axis
  scale_color_manual(values=c("white", "#FF8000")) +
  facet_grid(variable~okoregion, scales = "free", labeller = label_parse) +
  theme_bw() +
  xlab(NULL) + ylab("Monthly Flux (tonnes)") +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) +
  geom_text(data = T_testR, aes(y = 0.7, x = month, label = sign), size = 6, color = "black") 

ggsave("Figures/monthly_Flux_All4_bda.pdf", Plot, width = 8, height = 6, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/monthly_Flux_All4_bda.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/monthly_Flux_All4_bda.jpeg")
```

# Q/C Plots

```{r}
# Daily flux
daily_flux_all <- read.csv("Clean_Data/daily_flux_all.csv")

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

Data2 <- full_join(daily_flux_all, Station_Info) %>% drop_na() %>% 
  filter(year %in% c("2018", "2020")) %>% 
  filter(okoregion %in% c("Finnmark", "Ostlandet", "Vest")) %>% 
  mutate(month= month(month, label = T)) %>% 
  filter(month %in% c("Jun", "Jul", "Aug", "Sep", "Oct"))

Data2$variable <- factor(Data2$variable, 
    levels = c("DOC_mg_L", "Fe_ug_L", "Color_mg_L",  "TotP_ug_L", "TotN_ug_L", "NO3_ug_L", "Ca_mg_L"),
    labels = c("DOC", "Fe", "Color", "TotP", "TotN", "NO3", "Ca"))

Data2$okoregion <- factor(Data2$okoregion, 
    levels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Ostlandet", "Sorlandet", "Vest"),
    labels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Østlandet", "Sørlandet", "Vestlandet"))

plot <- Data2 %>% 
  ggplot(aes(x = log10(Q), y = log10(concentrations),group = interaction(site_id, year), color = factor(year))) +
  geom_point(size= 0.02, alpha = 0.05) +
  scale_color_manual(values=c("#FFCC66", "#264EFF")) +
  geom_smooth(method = "lm", size = 0.7) +
  facet_grid(variable~okoregion, scales = "free") +
  theme_bw() +
  labs(color = "year") +
  ylab(bquote('log'[10]~"Concentration")) + xlab(bquote('log'[10]~"Discharge"))

ggsave("Figures/daily_Con_v_QALL.pdf", plot, width = 6, height = 8, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/daily_Con_v_QALL.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/daily_Con_v_QALL.jpeg")




# Browning variables
Plot <- Data2 %>% 
  filter(variable %in% c("Ca_mg_L", "DOC_mg_L", "Fe_ug_L")) %>% 
  ggplot(aes(x = log10(Q), y = log10(concentrations),group = interaction(site_id, year), color = factor(year))) +
  geom_point(size= 0.02, alpha = 0.05) +
  scale_color_manual(values=c("#FFCC66", "#264EFF")) +
  geom_smooth(method = "lm", size = 0.7) +
  facet_grid(okoregion~variable, scales = "free") +
  theme_bw() +
  labs(color = "year") +
  ylab(bquote('log'[10]~"Concentration")) + xlab(bquote('log'[10]~"Discharge"))

ggsave("Figures/daily_flux_v_QBrown.pdf", Plot, width = 6, height = 6, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/daily_flux_v_QBrown.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/daily_flux_v_QBrown.jpeg")

# Nutrient variables
Plot2 <- Data2 %>% 
  filter(year %in% c("2018", "2020")) %>% 
  filter(variable %in% c("TotP_ug_L", "TotN_ug_L", "NO3_ug_L")) %>% 
  ggplot(aes(x = log10(Q), y = log10(concentrations), group = interaction(site_id, year), color = factor(year))) +
  geom_point(size= 0.02, alpha = 0.05) +
  scale_color_manual(values=c("#FFCC66", "#264EFF")) +
  geom_smooth(method = "lm", size = 0.7) +
  facet_grid(okoregion~variable, scales = "free") +
  theme_bw() +
  labs(color = "year") +
  ylab(bquote('log'[10]~"Concentration")) + xlab(bquote('log'[10]~"Discharge"))

ggsave("Figures/daily_flux_v_QNut.pdf", Plot2, width = 6, height = 6, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/daily_flux_v_QNut.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/daily_flux_v_QNut.jpeg")
```

```{r}
# Daily flux
daily_flux_all <- read.csv("Clean_Data/daily_flux_all.csv")

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

Data3 <- full_join(daily_flux_all, Station_Info) %>% drop_na() %>% 
  filter(year %in% c("2019", "2021")) %>% 
  mutate(month= month(month, label = T)) %>% 
  filter(month %in% c("Jun", "Jul", "Aug", "Sep", "Oct"))
  
### 2019/2021
# Browning variables
Plot3 <- Data3 %>% 
  filter(variable %in% c("Ca_mg_L", "DOC_mg_L", "Fe_ug_L")) %>% 
  ggplot(aes(x = log10(Q), y = log10(concentrations),group = interaction(site_id, year), color = factor(year))) +
  geom_point(size= 0.02, alpha = 0.05) +
  scale_color_manual(values=c("#3399FF", "#FF8000")) +
  geom_smooth(method = "lm", size = 0.7) +
  facet_grid(okoregion~variable, scales = "free") +
  theme_bw() +
  labs(color = "year") +
  ylab(bquote('log'[10]~"Concentration")) + xlab(bquote('log'[10]~"Discharge"))

ggsave("Figures/daily_flux_v_QBrown_2019.pdf", Plot3, width = 6, height =6, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/daily_flux_v_QBrown_2019.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/daily_flux_v_QBrown_2019.jpeg")

# Nutrient variables
Plot4 <- Data3 %>% 
  filter(variable %in% c("TotP_ug_L", "TotN_ug_L", "NO3_ug_L")) %>% 
  ggplot(aes(x = log10(Q), y = log10(concentrations), group = interaction(site_id, year), color = factor(year))) +
  geom_point(size= 0.02, alpha = 0.05) +
  scale_color_manual(values=c("#3399FF", "#FF8000")) +
  geom_smooth(method = "lm", size = 0.7) +
  facet_grid(okoregion~variable, scales = "free") +
  theme_bw() +
  labs(color = "year") +
  ylab(bquote('log'[10]~"Concentration")) + xlab(bquote('log'[10]~"Discharge"))

ggsave("Figures/daily_flux_v_QNut_2019.pdf", Plot4, width = 6, height = 6, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/daily_flux_v_QNut_2019.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/daily_flux_v_QNut_2019.jpeg")
```

```{r}
# DOC
Plot <- full_join(daily_flux_all, Station_Info) %>% drop_na() %>% 
  filter(!year %in% c("2017", "2022")) %>% 
  filter(variable %in% c("DOC_mg_L")) %>% 
  ggplot(aes(x = log10(Q), y = log10(flux), color = as.character(year))) +
  geom_point(size =0.1) +
  facet_wrap(~site_id, scales = "free", ncol = 4) +
  theme_bw() 

ggsave("Figures/daily_flux_v_Q_DOC.pdf", Plot, width = 8, height = 20, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/daily_flux_v_Q_DOC.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/daily_flux_v_Q_DOC.jpeg")
```

```{r}
# OLD figure----Monthly data. 
Water_Chem_select <- read_csv("Clean_Data/Water_Chem_select.csv")

# Ca
Data <- Water_Chem_select %>% 
  mutate(year = year(Date)) %>% 
  mutate(month = month(Date)) %>% 
  mutate(day = day(Date)) %>% 
  mutate(Date = make_date(month, day)) %>% 
  filter(year %in% c("2018", "2020")) %>% 
  dplyr::select(c(site_id, Q, Date, year,coniferous_forest, DOC_mg_L, NO3_ug_L, Ca_mg_L)) %>% 
  pivot_longer(col = -c(site_id, Q, Date, year, coniferous_forest), values_to = "measurement", names_to = "Variable")


Plot <- Data %>% 
  ggplot(aes(x = log10(Q), y = log10(measurement), color = coniferous_forest)) + 
  geom_point(size = 1.0) +
  geom_smooth(method = "lm", se = T, color = "blue") +
  facet_grid(Variable ~ year, labeller = label_parsed, scales = "free") +
  theme_bw() +
  xlab("log10(Q)") + ylab("log10(Concentration)")

ggsave("Figures/Q_C.pdf", Plot, width = 6, height = 6, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Q_C.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Q_C.jpeg")
```

# Slope and intercepts

```{r}
# Daily Concentrations (interpolated and summed back to monthly. 

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, okoregion)

concentrations_daily <- read_csv("Clean_Data/daily_flux_all.csv") %>% 
  dplyr::select(site_id, month, date, year, variable, concentrations) 
  
gwb_q_daily <- read_csv("Clean_Data/Intermediate/Drought_Data_daily.csv") %>%
  dplyr::select(c(site_id, par, datetime, value_mean)) %>% 
  separate(datetime, c("date", "Time"), sep = " ") %>% 
  filter(par =="gwb_q") %>% 
  pivot_wider(names_from ="par", values_from = "value_mean") %>% 
  dplyr::select(site_id, date, gwb_q) %>% 
  mutate(date = ymd(date)) 

Data2 <- full_join(concentrations_daily, gwb_q_daily)
Data <- full_join(Data2, Station_Info) %>%  distinct() %>% drop_na()

Plot <- Data %>% 
  filter(!year %in% c("2017", "2022")) %>% 
  filter(variable %in% c("DOC_mg_L")) %>% 
  ggplot(aes(x = log10(gwb_q), y = log10(concentrations), color = okoregion)) + 
  geom_point(size = 0.05) +
  #geom_smooth(method = "lm", se = T, size = 0.1) +
  facet_grid(variable ~ year, labeller = label_parsed, scales = "free") +
  theme_bw() +
  xlab("log10(Q)") + ylab("log10(Concentration)")

ggsave("Figures/Q_C_daily.pdf", Plot, width = 6, height = 12, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Q_C_daily.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Q_C_daily.jpeg")



###### By group
Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

# QC: 2018/2020

concentrations_daily <- read_csv("Clean_Data/daily_flux_all.csv") %>% 
  dplyr::select(site_id, date, year, variable, concentrations) %>% 
   filter(year %in% c("2018", "2019", "2020", "2021"))

gwb_q_daily <- read_csv("Clean_Data/Intermediate/Drought_Data_daily.csv") %>%
  dplyr::select(c(site_id, par, datetime, value_mean)) %>% 
  separate(datetime, c("date", "Time"), sep = " ") %>% 
  filter(par =="gwb_q") %>% 
  pivot_wider(names_from ="par", values_from = "value_mean") %>% 
  dplyr::select(site_id, date, gwb_q) %>% 
  mutate(date = ymd(date)) %>% 
  mutate(year = year(date), month = month(date, label = TRUE)) %>% 
  filter(year %in% c("2018", "2019", "2020", "2021"))

Data2 <- full_join(concentrations_daily, gwb_q_daily)
Data <- full_join(Data2, Station_Info) %>%  distinct() %>% drop_na() %>% 
  mutate(year = year(date), month = month(date, label = TRUE)) %>% 
  filter(group %in% c("'18/'20")) %>% 
  filter(year %in% c("2018", "2020")) %>% 
  mutate(drought_time =ifelse(grepl("Jan|Feb|Mar|Apr", month), "Before", "After")) %>%
  mutate(drought_time =ifelse(grepl("May|Jun|Jul", month), "During", drought_time)) %>%
  dplyr::select(c(site_id, date, year, gwb_q, okoregion, variable, concentrations, drought_time)) %>% 
  mutate(variable = str_replace_all(variable, "_ug_L", "")) %>%
  mutate(variable = str_replace_all(variable, "_mg_L", "")) %>% 
  filter(variable %in% c("Ca", "Fe", "DOC", "TotP", "TotN", "NO3"))
  

# Ca
Plot <- Data %>% 
  filter(variable == "Ca_mg_L") %>% 
  ggplot(aes(x = log10(gwb_q), y = log10(concentrations), color = drought_time)) + 
  geom_point(size = 0.05) +
  facet_grid(year~okoregion, labeller = label_parsed, scales = "free") +
  theme_bw() +
  xlab("log10(Q)") + ylab("log10(Concentration)")

ggsave("Figures/QC_18_20_ca.pdf", Plot, width = 5, height = 4, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/QC_18_20_ca.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/QC_18_20_ca.jpeg")

ggsave("Figures/QC_18_20.pdf", Plot, width = 7, height = 15, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/QC_18_20.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/QC_18_20.jpeg")


# Extract slope and intercepts of Q/C plots. 
Plot <- Data %>% 
  ggplot(aes(x = log10(gwb_q), y = log10(concentrations), color = drought_time)) + 
  geom_point(size = 0.05) +
  #geom_smooth(method = "lm", se = T, size = 0.1) +
  facet_grid(year~variable, labeller = label_parsed, scales = "free") +
  theme_bw() +
  xlab("log10(Q)") + ylab("log10(Concentration)")


# Extract slope and intercept from all plots

Extract_df <- Data %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(gwb_q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, year, variable) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

# Extract slope and intercept from all plots broken down into before, during and after drought. 

Extract_drought_df <- Data %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(gwb_q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, year, variable, drought_time) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

Extract_drought_df2 <- full_join(Extract_drought_df, Data) %>% 
  group_by(year, okoregion, drought_time, variable) %>%
  summarise_at(vars(matches("slope|intercept")), funs(mean=mean))

Extract_drought_df3 <- full_join(Extract_drought_df2, Extract_drought_df) 

Extract_drought_df3$drought_time <- factor(Extract_drought_df3$drought_time,
                        levels = c("Before", "During", "After"))


lm_18_20 <- Extract_drought_df3 %>% 
  ggplot(aes(fill = drought_time, shape = factor(year))) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  scale_shape_manual(values=c(21, 22))+
  geom_point(aes(x = intercept, y = slope), size = 0.2, alpha = 0.3) +
  stat_summary(fun.data = mean_cl_boot, conf.int = .95,
                 aes(x =intercept_mean, y = slope),
                 geom = "errorbar", width = 0.05, alpha = 0.8) +
  stat_summaryh(fun.data = mean_cl_boot_h, conf.int = .95,
                 aes(x = intercept, y = slope_mean),
                 geom ="errorbarh", width = 0.02, alpha = 0.8) +
  geom_point(aes(x = intercept_mean, y = slope_mean), size = 2.5, alpha = 0.9) +
  facet_grid2(variable~okoregion, scales="free") +
  guides(fill = guide_legend(override.aes=list(shape = 21)), shape = guide_legend(override.aes=list(color="black"))) + 
  theme_bw() + labs(fill = "Drought", shape = "year")

ggsave("Figures/lm_18_20.pdf", lm_18_20, width = 6, height = 18, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/lm_18_20.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/lm_18_20.jpeg")



### 2019/2021
Data_19 <- full_join(Data2, Station_Info) %>%  distinct() %>% drop_na() %>% 
  mutate(year = year(date), month = month(date, label = TRUE)) %>% 
  filter(group %in% c("'19/'21")) %>% 
  filter(year %in% c("2019", "2021")) %>% 
  mutate(drought_time =ifelse(grepl("Jan|Feb|Mar|Apr", month), "Before", "After")) %>%
  mutate(drought_time =ifelse(grepl("May|Jun|Jul", month), "During", drought_time)) %>%
  dplyr::select(c(site_id, date, year, gwb_q, okoregion, variable, concentrations, drought_time)) %>% 
  mutate(variable = str_replace_all(variable, "_ug_L", "")) %>%
  mutate(variable = str_replace_all(variable, "_mg_L", ""))


# Extract slope and intercepts of Q/C plots. 
Plot <- Data_19 %>% 
  ggplot(aes(x = log10(gwb_q), y = log10(concentrations), color = drought_time)) + 
  geom_point(size = 0.05) +
  #geom_smooth(method = "lm", se = T, size = 0.1) +
  facet_grid(year~variable, labeller = label_parsed, scales = "free") +
  theme_bw() +
  xlab("log10(Q)") + ylab("log10(Concentration)")


# Extract slope and intercept from all plots

Extract_df_19 <- Data_19 %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(gwb_q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, year, variable) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

# Extract slope and intercept from all plots broken down into before, during and after drought. 

Extract_drought_df_19 <- Data_19 %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(gwb_q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, year, variable, drought_time) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

Extract_drought_df2_19 <- full_join(Extract_drought_df_19, Data_19) %>% 
  group_by(year, okoregion, drought_time, variable) %>%
  summarise_at(vars(matches("slope|intercept")), funs(mean=mean))

Extract_drought_df3_19 <- full_join(Extract_drought_df2_19, Extract_drought_df_19)

Extract_drought_df3_19$drought_time <- factor(Extract_drought_df3_19$drought_time,
                        levels = c("Before", "During", "After"))

lm_19_21 <- Extract_drought_df3_19 %>% 
  ggplot(aes(fill = drought_time, shape = factor(year))) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  scale_shape_manual(values=c(21, 22))+
  geom_point(aes(x = intercept, y = slope), size = 0.2, alpha = 0.3) +
  stat_summary(fun.data = mean_cl_boot, conf.int = .95,
                 aes(x =intercept_mean, y = slope),
                 geom = "errorbar", width = 0.05, alpha = 0.8) +
  stat_summaryh(fun.data = mean_cl_boot_h, conf.int = .95,
                 aes(x = intercept, y = slope_mean),
                 geom ="errorbarh", width = 0.02, alpha = 0.8) +
  geom_point(aes(x = intercept_mean, y = slope_mean), size = 2.5, alpha = 0.9) +
  facet_grid2(variable~okoregion, scales="free") +
  guides(fill = guide_legend(override.aes=list(shape = 21)), shape = guide_legend(override.aes=list(color="black"))) + 
  theme_bw() + labs(fill = "Drought", shape = "year")

ggsave("Figures/lm_19_21.pdf", lm_19_21, width = 7, height = 18, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/lm_19_21.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/lm_19_21.jpeg")


### ALl
### 2019/2021
Data_ALL <- full_join(Data2, Station_Info) %>%  distinct() %>% drop_na() %>% 
  mutate(year = year(date), month = month(date, label = TRUE)) %>% 
  filter(group %in% c("'18/'19/'20/'21")) %>% 
  filter(year %in% c("2018", "2019","2020", "2021")) %>% 
  mutate(drought_time =ifelse(grepl("Jan|Feb|Mar|Apr", month), "Before", "After")) %>%
  mutate(drought_time =ifelse(grepl("May|Jun|Jul", month), "During", drought_time)) %>%
  dplyr::select(c(site_id, date, year, gwb_q, okoregion, variable, concentrations, drought_time)) %>% 
  mutate(variable = str_replace_all(variable, "_ug_L", "")) %>%
  mutate(variable = str_replace_all(variable, "_mg_L", ""))

# Extract slope and intercepts of Q/C plots. 
Plot <- Data_ALL %>% 
  ggplot(aes(x = log10(gwb_q), y = log10(concentrations), color = drought_time)) + 
  geom_point(size = 0.05) +
  #geom_smooth(method = "lm", se = T, size = 0.1) +
  facet_grid(year~variable, labeller = label_parsed, scales = "free") +
  theme_bw() +
  xlab("log10(Q)") + ylab("log10(Concentration)")


# Extract slope and intercept from all plots

Extract_df_ALL <- Data_ALL %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(gwb_q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, year, variable) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

# Extract slope and intercept from all plots broken down into before, during and after drought. 

Extract_drought_df_ALL <- Data_ALL %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(gwb_q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, year, variable, drought_time) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

Extract_drought_df2_ALL <- full_join(Extract_drought_df_ALL, Data_ALL) %>% 
  group_by(year, okoregion, drought_time, variable) %>%
  summarise_at(vars(matches("slope|intercept")), funs(mean=mean))

Extract_drought_df3_ALL <- full_join(Extract_drought_df2_ALL, Extract_drought_df_ALL) 

Extract_drought_df3_ALL$drought_time <- factor(Extract_drought_df3_ALL$drought_time,
                        levels = c("Before", "During", "After"))

lm_ALL <- Extract_drought_df3_ALL %>% 
  ggplot(aes(fill = drought_time, shape = factor(year))) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  scale_shape_manual(values=c(21, 22, 23, 24))+
  geom_point(aes(x = intercept, y = slope), size = 0.2, alpha = 0.3) +
  stat_summary(fun.data = mean_cl_boot, conf.int = .95,
                 aes(x =intercept_mean, y = slope),
                 geom = "errorbar", width = 0.05, alpha = 0.8) +
  stat_summaryh(fun.data = mean_cl_boot_h, conf.int = .95,
                 aes(x = intercept, y = slope_mean),
                 geom ="errorbarh", width = 0.02, alpha = 0.8) +
  geom_point(aes(x = intercept_mean, y = slope_mean), size = 2.5, alpha = 0.9) +
  facet_grid2(variable~okoregion, scales="free") +
  guides(fill = guide_legend(override.aes=list(shape = 21)), shape = guide_legend(override.aes=list(color="black"))) + 
  theme_bw() + labs(fill = "Drought", shape = "year")

ggsave("Figures/lm_ALL.pdf", lm_ALL, width = 7, height = 18, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/lm_ALL.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/lm_ALL.jpeg")


###### dot plot

# QC: 2018/2020

concentrations_daily <- read_csv("Clean_Data/daily_flux_all.csv") %>% 
  dplyr::select(site_id, date, year, variable, concentrations) %>% 
   filter(year %in% c("2018", "2019", "2020", "2021"))

gwb_q_daily <- read_csv("Clean_Data/Intermediate/Drought_Data_daily.csv") %>%
  dplyr::select(c(site_id, par, datetime, value_mean)) %>% 
  separate(datetime, c("date", "Time"), sep = " ") %>% 
  filter(par =="gwb_q") %>% 
  pivot_wider(names_from ="par", values_from = "value_mean") %>% 
  dplyr::select(site_id, date, gwb_q) %>% 
  mutate(date = ymd(date)) %>% 
  mutate(year = year(date), month = month(date, label = TRUE)) %>% 
  filter(year %in% c("2018", "2019", "2020", "2021"))

Data2 <- full_join(concentrations_daily, gwb_q_daily)
Data <- full_join(Data2, Station_Info) %>%  distinct() %>% drop_na() %>% 
  mutate(year = year(date), month = month(date, label = TRUE)) %>% 
  mutate(drought_time =ifelse(grepl("Jan|Feb|Mar|Apr", month), "Before", "After")) %>%
  mutate(drought_time =ifelse(grepl("May|Jun|Jul", month), "During", drought_time)) %>%
  dplyr::select(c(site_id, date, year, group, gwb_q, okoregion, variable, concentrations, drought_time)) %>% 
  mutate(variable = str_replace_all(variable, "_ug_L", "")) %>%
  mutate(variable = str_replace_all(variable, "_mg_L", ""))
```

# Extract Slope and intercepts

```{r}
# Extract slope and intercept from all plots broken down into before, during and after drought. 

# Daily flux
daily_flux_all <- read.csv("Clean_Data/daily_flux_all.csv")

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

Data2 <- full_join(daily_flux_all, Station_Info) %>% drop_na() %>% 
  filter(group %in% c("'18/'20")) %>% 
  filter(year %in% c("2018","2020")) %>% 
  filter(okoregion %in% c("Finnmark", "Ostlandet", "Vest")) %>% 
  mutate(month= month(month, label = T)) %>% 
  filter(month %in% c("Jun", "Jul", "Aug", "Sep", "Oct"))

Extract_drought_df <- Data2 %>% 
  distinct() %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(Q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, year, variable) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

Extract_drought_df2 <- full_join(Extract_drought_df, Data2) 

Extract_drought_df3 <- full_join(Extract_drought_df2, Extract_drought_df) %>% 
  dplyr::select(c(site_id, variable, slope, intercept, okoregion, year, group)) %>% distinct()

Extract_drought_df3$variable <- factor(Extract_drought_df3$variable, 
                                       levels = c("DOC_mg_L", "Fe_ug_L", "Color_mg_L",  "TotP_ug_L", "TotN_ug_L", "NO3_ug_L", "Ca_mg_L"),
                                       labels = c("DOC", "Fe", "Color", "TotP", "TotN", "NO3", "Ca"))

Extract_drought_df3$okoregion <- factor(Extract_drought_df3$okoregion, 
                                       levels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Ostlandet", "Sorlandet", "Vest"),
                                       labels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Østlandet", "Sørlandet", "Vestlandet"))


# 18/20
# Intercept
lm_dots_18_Inter <- Extract_drought_df3 %>% 
  ggplot(aes(x = intercept, y = factor(variable), color = factor(year))) +
  stat_summary(fun.data = "mean_cl_boot", size = 0.8) +
  scale_color_manual(values=c("#FFCC66", "#264EFF")) +
  facet_grid(~okoregion, scales="free") +
  theme_bw() + labs(color = "year") + 
  theme(legend.position="none") +
  geom_vline(xintercept = 0, linetype="dotted", color = "gray45", size=1.5) +
  xlab("Q/C Intercept") + ylab(NULL) + 
  theme(text = element_text(size = 16)) +
  scale_y_discrete(limits = rev(levels(Extract_drought_df3$variable))) 
  
# Slope
lm_dots_18_S <- Extract_drought_df3 %>% 
  filter(group %in% c("'18/'20")) %>% 
  filter(year %in% c("2018","2020")) %>% 
  ggplot(aes(x = slope, y = factor(variable), color = factor(year))) +
  stat_summary(fun.data = "mean_cl_boot", size = 0.8) +
  scale_color_manual(values=c("#FFCC66", "#264EFF")) +
  facet_grid(~okoregion, scales="free") +
  theme_bw() + labs(color = "year") + 
  theme(legend.position="bottom") +
  geom_vline(xintercept = 0, linetype="dotted", color = "gray45", size=1.5) +
  xlab("Q/C Slope") + ylab(NULL) + 
  theme(text = element_text(size = 16)) +
  scale_y_discrete(limits = rev(levels(Extract_drought_df3$variable))) 
  
p <- (lm_dots_18_Inter/lm_dots_18_S) + plot_annotation(tag_levels = 'A')

ggsave("Figures/lm_dots_18.pdf", p, width = 10, height = 8, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/lm_dots_18.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/lm_dots_18.jpeg")


# 19/21
Data3 <- full_join(daily_flux_all, Station_Info) %>% drop_na() %>% 
  filter(year %in% c("2019", "2021")) %>% 
  mutate(month= month(month, label = T)) %>% 
  filter(month %in% c("Jun", "Jul", "Aug", "Sep", "Oct"))

Extract_drought_df <- Data3 %>% 
  distinct() %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(Q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, year, variable) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

Extract_drought_df2 <- full_join(Extract_drought_df, Data3) 

Extract_drought_df3 <- full_join(Extract_drought_df2, Extract_drought_df) %>% 
  dplyr::select(c(site_id, variable, slope, intercept, okoregion, year, group)) %>% distinct()

Extract_drought_df3$variable <- factor(Extract_drought_df3$variable, 
                                       levels = c("DOC_mg_L", "Fe_ug_L", "Color_mg_L",  "TotP_ug_L", "TotN_ug_L", "NO3_ug_L", "Ca_mg_L"),
                                       labels = c("DOC", "Fe", "Color", "TotP", "TotN", "NO3", "Ca"))

Extract_drought_df3$okoregion <- factor(Extract_drought_df3$okoregion, 
                                       levels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Ostlandet", "Sorlandet", "Vest"),
                                       labels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Østlandet", "Sørlandet", "Vestlandet"))

# Intercept
lm_dots_19_Inter <- Extract_drought_df3 %>% 
  filter(group %in% c("'19/'21")) %>% 
  filter(year %in% c("2019","2021")) %>% 
  ggplot(aes(x = slope, y = factor(variable), color = factor(year))) +
  stat_summary(fun.data = "mean_cl_boot", size = 0.8) +
  scale_color_manual(values=c("#3399FF", "#FF8000")) +
  facet_grid(~okoregion, scales="free") +
  theme_bw() + labs(color = "year") + 
  theme(legend.position="none") +
  geom_vline(xintercept = 0, linetype="dotted", color = "gray45", size=1.5) +
  xlab("Q/C Intercept") + ylab(NULL) + 
  theme(text = element_text(size = 16)) +
  scale_y_discrete(limits = rev(levels(Extract_drought_df3$variable))) 

# Slope
lm_dots_19_S <- Extract_drought_df3 %>% 
  filter(group %in% c("'19/'21")) %>% 
  filter(year %in% c("2019","2021")) %>% 
  ggplot(aes(x = slope, y = factor(variable), color = factor(year))) +
  stat_summary(fun.data = "mean_cl_boot", size = 0.8) +
  scale_color_manual(values=c("#3399FF", "#FF8000")) +
  facet_grid(~okoregion, scales="free") +
  theme_bw() + labs(color = "year") + 
  theme(legend.position="bottom") +
  geom_vline(xintercept = 0, linetype="dotted", color = "gray45", size=1.5) +
  xlab("Q/C Slope") + ylab(NULL) + 
  theme(text = element_text(size = 16)) +
  scale_y_discrete(limits = rev(levels(Extract_drought_df3$variable))) 
  
p <- (lm_dots_19_Inter/lm_dots_19_S)  + plot_annotation(tag_levels = 'A')

ggsave("Figures/lm_dots_19.pdf", p, width = 9, height = 8, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/lm_dots_19.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/lm_dots_19.jpeg")


#ALL

Data4 <- full_join(daily_flux_all, Station_Info) %>% drop_na() %>% 
  filter(group %in% c("'18/'19/'20/'21")) %>% 
  filter(year %in% c("2019", "2021", "2018", "2020")) %>% 
  mutate(month= month(month, label = T)) %>% 
  filter(month %in% c("Jun", "Jul", "Aug", "Sep", "Oct"))

Extract_drought_df <- Data4 %>% 
  distinct() %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(Q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, year, variable) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

Extract_drought_df2 <- full_join(Extract_drought_df, Data4)

Extract_drought_df3 <- full_join(Extract_drought_df2, Extract_drought_df) %>% 
  dplyr::select(c(site_id, variable, slope, intercept, okoregion, year, group)) %>% distinct()

Extract_drought_df3$variable <- factor(Extract_drought_df3$variable, 
                                       levels = c("DOC_mg_L", "Fe_ug_L", "Color_mg_L",  "TotP_ug_L", "TotN_ug_L", "NO3_ug_L", "Ca_mg_L"),
                                       labels = c("DOC", "Fe", "Color", "TotP", "TotN", "NO3", "Ca"))

Extract_drought_df3$okoregion <- factor(Extract_drought_df3$okoregion, 
                                       levels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Ostlandet", "Sorlandet", "Vest"),
                                       labels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Østlandet", "Sørlandet", "Vestlandet"))

# Intercept
lm_dots_ALL_Inter <- Extract_drought_df3 %>% 
  filter(group %in% c("'18/'19/'20/'21")) %>% 
  filter(year %in% c("2018","2019", "2020","2021")) %>% 
  ggplot(aes(x = intercept, y = factor(variable), color = factor(year))) +
  stat_summary(fun.data = "mean_cl_boot", size = 0.8) +
  scale_color_manual(values=c("#FFCC66", "#3399FF", "#264EFF", "#FF8000")) +
  facet_grid(~okoregion, scales="free") +
  theme_bw() + labs(color = "year") + 
  theme(legend.position="none") +
  geom_vline(xintercept = 0, linetype="dotted", color = "gray45", size=1.5) +
  xlab("Q/C Intercept") + ylab(NULL) + 
  theme(text = element_text(size = 16)) +
  scale_y_discrete(limits = rev(levels(Extract_drought_df3$variable))) 

# Slope
lm_dots_ALL_S <- Extract_drought_df3 %>% 
  filter(group %in% c("'18/'19/'20/'21")) %>% 
  filter(year %in% c("2018","2019", "2020","2021")) %>% 
  ggplot(aes(x = slope, y = factor(variable), color = factor(year))) +
  stat_summary(fun.data = "mean_cl_boot", size = 0.8) +
  scale_color_manual(values=c("#FFCC66", "#3399FF", "#264EFF", "#FF8000")) +
  facet_grid(~okoregion, scales="free") +
  theme_bw() + labs(color = "year") + 
  geom_vline(xintercept = 0, linetype="dotted", color = "gray45", size=1.5) +
  xlab("Q/C Slope") + ylab(NULL) + 
  theme(text = element_text(size = 16)) +
  scale_y_discrete(limits = rev(levels(Extract_drought_df3$variable))) 
  
p <- (lm_dots_ALL_Inter/lm_dots_ALL_S) + plot_annotation(tag_levels = 'A') + plot_layout(guides = "collect")

ggsave("Figures/lm_dots_ALL.pdf", p, width = 7, height = 6, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/lm_dots_ALL.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/lm_dots_ALL.jpeg")
```

# Q/C plot for setting up hypotheses

```{r}
# Extract slope and intercept from all plots broken down into before, during and after drought. 
library(Hmisc)
library(ggstance)
# Daily flux
daily_flux_all <- read.csv("Clean_Data/daily_flux_all.csv")

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

Data2 <- full_join(daily_flux_all, Station_Info) %>% drop_na() %>% 
  filter(group %in% c("'18/'20", "'19/'21")) %>% 
  filter(year %in% c("2018","2020", "2019","2021")) 

Extract_drought_df <- Data2 %>% 
  distinct() %>% 
  group_by(site_id, date, variable) %>% 
  mutate(X = log10(Q), Y = log10(concentrations)) %>% 
  ungroup() %>% drop_na() %>% 
  group_by(site_id, group, variable) %>% 
  do({mod = lm(Y ~ X, data =.) 
  data_frame(slope = coef(mod)[2], intercept = coef(mod)[1], r2 = summary(mod)$r.squared)}) 

Extract_drought_df2 <- full_join(Extract_drought_df, Data2) 
Extract_drought_df3 <- full_join(Extract_drought_df2, Extract_drought_df) %>% 
  dplyr::select(c(site_id, variable, slope, okoregion, group)) %>% distinct()

Extract_drought_df3$variable <- factor(Extract_drought_df3$variable, 
                                       levels = c("DOC_mg_L", "Fe_ug_L", "Color_mg_L",  "TotP_ug_L", "TotN_ug_L", "NO3_ug_L", "Ca_mg_L"),
                                       labels = c("DOC", "Fe", "Color", "TotP", "TotN", "NO3", "Ca"))

Extract_drought_df3$okoregion <- factor(Extract_drought_df3$okoregion, 
                                       levels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Ostlandet", "Sorlandet", "Vest"),
                                       labels = c("Finnmark", "Midt-Norge", "Nord-Norge ytre",  "Østlandet", "Sørlandet", "Vestlandet"))

Extract_drought_df3$group <- factor(Extract_drought_df3$group, 
                                       levels = c("'18/'20", "'19/'21"),
                                       labels = c("2018 & 2020", "2019 & 2021"))

# Slope
lm_dots_hypo <- Extract_drought_df3 %>% 
  distinct() %>% 
  ggplot(aes(x = slope, y = factor(variable), color = okoregion)) +
  stat_summary(fun.data = "mean_cl_boot", size = 0.8) +
  facet_grid(~group, scales="free") +
  theme_bw() + 
  geom_vline(xintercept = 0, linetype="dotted", color = "gray45", size=1.5) +
  xlab("Q/C Slope") + ylab(NULL) + 
  scale_y_discrete(limits = rev(levels(Extract_drought_df3$variable))) +
  theme(text = element_text(size = 16)) + labs(color = "Økoregion")

ggsave("Figures/Q_C_Slope_hypothes.pdf", lm_dots_hypo, width = 9, height = 4, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Q_C_Slope_hypothes.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Q_C_Slope_hypothes.jpeg")
```

# Corrplot Slope & intercept

```{r}

Extract_drought_df3 <- read_csv("Clean_Data/Extract_drought.csv") %>% 
  dplyr::select(-c(slope_mean, intercept_mean, r2)) %>% 
  pivot_longer(cols= c(slope, intercept), names_to = "Envar", values_to= 'Envar_Measurement') 

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  pivot_longer(cols= -c(site_id, rapportnavn, fylke, okoregion, group), names_to = "Predict", values_to= 'Predict_Measurement') 

corData <- full_join(Extract_drought_df3, Station_Info) %>% drop_na()

data_nest <- corData %>% group_by(group, okoregion, year, variable, Envar,Predict) %>% nest() 
str(slice(data_nest, 1))
cor_fun <- function(data) cor.test(data$Envar_Measurement, data$Predict_Measurement, method = "pearson", adjust = "bonferroni") %>% tidy() #bonferroni
data_nest <- mutate(data_nest, model = map(data, cor_fun))
str(slice(data_nest, 1))
corr_pr <- dplyr::select(data_nest, -data) %>% unnest()
corr_pr <- mutate(corr_pr, sig = ifelse(p.value <0.05, "Sig.", "Non Sig."))


corr_pr_18 <- corr_pr %>% 
  filter(group %in% c("'18/'20")) %>% 
  filter(year %in% c("2018","2020")) %>% 
  drop_na(estimate)

corr_pr_18$Predict <- factor(corr_pr_18$Predict, levels = c("other", "woodland_scrub", "agriculture", "mixed_forest", "coniferous_forest", "water_bodies", "peat_bogs", "glacier", "sparse_vegetation", "moors_and_heathland", "bare_rocks", "broad_leaved_forest", "longitude","latitude","min_2018_gwb_sssrel","mean_annual_gwb_sssrel", "mean_annual_gwb_q", "sum_annual_rr", "mean_annual_tm", "mean_slope", "mean_elevation", "area_km2"), labels = c("other", "woodland_scrub", "agriculture", "mixed_forest", "coniferous_forest", "water_bodies", "peat_bogs", "glacier", "sparse_vegetation", "moors_and_heathland", "bare_rocks", "broad_leaved_forest", "longitude","latitude","min_2018_gwb_sssrel","m_an_gwb_sssrel", "m_an_gwb_q", "sum_an_rr", "m_an_tm", "m_slope", "m_elevation", "area_km2"))

corr_pr_19 <- corr_pr %>% 
  filter(group %in% c("'19/'21")) %>% 
  filter(year %in% c("2019","2021")) %>% 
  drop_na(estimate)

corr_pr_19$Predict <- factor(corr_pr_19$Predict, levels = c("other", "woodland_scrub", "agriculture", "mixed_forest", "coniferous_forest", "water_bodies", "peat_bogs", "glacier", "sparse_vegetation", "moors_and_heathland", "bare_rocks", "broad_leaved_forest", "longitude","latitude","min_2018_gwb_sssrel","mean_annual_gwb_sssrel", "mean_annual_gwb_q", "sum_annual_rr", "mean_annual_tm", "mean_slope", "mean_elevation", "area_km2"), labels = c("other", "woodland_scrub", "agriculture", "mixed_forest", "coniferous_forest", "water_bodies", "peat_bogs", "glacier", "sparse_vegetation", "moors_and_heathland", "bare_rocks", "broad_leaved_forest", "longitude","latitude","min_2018_gwb_sssrel","m_an_gwb_sssrel", "m_an_gwb_q", "sum_an_rr", "m_an_tm", "m_slope", "m_elevation", "area_km2"))

corr_pr_ALL <- corr_pr %>% 
  filter(group %in% c("'18/'19/'20/'21")) %>% 
  filter(year %in% c("2018","2019", "2020","2021")) %>% 
  drop_na(estimate)

corr_pr_ALL$Predict <- factor(corr_pr_ALL$Predict, levels = c("other", "woodland_scrub", "agriculture", "mixed_forest", "coniferous_forest", "water_bodies", "peat_bogs", "glacier", "sparse_vegetation", "moors_and_heathland", "bare_rocks", "broad_leaved_forest", "longitude","latitude","min_2018_gwb_sssrel","mean_annual_gwb_sssrel", "mean_annual_gwb_q", "sum_annual_rr", "mean_annual_tm", "mean_slope", "mean_elevation", "area_km2"), labels = c("other", "woodland_scrub", "agriculture", "mixed_forest", "coniferous_forest", "water_bodies", "peat_bogs", "glacier", "sparse_vegetation", "moors_and_heathland", "bare_rocks", "broad_leaved_forest", "longitude","latitude","min_2018_gwb_sssrel","m_an_gwb_sssrel", "m_an_gwb_q", "sum_an_rr", "m_an_tm", "m_slope", "m_elevation", "area_km2"))



############## Slope #########################
corr_slope_18 <- corr_pr_18 %>% filter(Envar %in% c("slope")) 
corr_slope_19 <- corr_pr_19 %>% filter(Envar %in% c("slope")) 
corr_slope_ALL <- corr_pr_ALL %>% filter(Envar %in% c("slope")) 

# 2018/2020
Figure <- ggplot() +
  geom_tile(data = corr_slope_18,
            aes(variable, Predict, fill = estimate),
            size = 1,
            colour = "white")+
  geom_tile(data = filter(corr_slope_18, sig == "Sig."),
            aes(variable, Predict),
            size = 1,
            colour = "black",
            fill = "transparent")+
  geom_text(data = corr_slope_18,
            aes(variable, Predict, label = round(estimate, 2),
                fontface = ifelse(sig == "Sig.", "bold", "plain")))+
  scale_fill_gradient2(breaks = seq(-1, 1, 0.2))+
  labs(x = "", y = "", fill = "", p.value = "")+
  theme_minimal()+
  facet_grid(year~okoregion) +
  theme(panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(size = 10)) + labs(fill = "Pearson's\nCorrelation") + 
  theme(text = element_text(size = 16))

ggsave("Figures/Corrplot_18.pdf", Figure, width = 15, height = 10, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Corrplot_18.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Corrplot_18.jpeg")


# 2019/2021
Figure <- ggplot() +
  geom_tile(data = corr_slope_19,
            aes(variable, Predict, fill = estimate),
            size = 1,
            colour = "white")+
  geom_tile(data = filter(corr_slope_19, sig == "Sig."),
            aes(variable, Predict),
            size = 1,
            colour = "black",
            fill = "transparent")+
  geom_text(data = corr_slope_19,
            aes(variable, Predict, label = round(estimate, 2),
                fontface = ifelse(sig == "Sig.", "bold", "plain")))+
  scale_fill_gradient2(breaks = seq(-1, 1, 0.2))+
  labs(x = "", y = "", fill = "", p.value = "")+
  theme_minimal()+
  facet_grid(year~okoregion) +
  theme(panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(size = 10)) + labs(fill = "Pearson's\nCorrelation") + 
  theme(text = element_text(size = 16))

ggsave("Figures/Corrplot_19.pdf", Figure, width = 15, height = 10, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Corrplot_19.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Corrplot_19.jpeg")


# ALL
Figure <- ggplot() +
  geom_tile(data = corr_slope_ALL,
            aes(variable, Predict, fill = estimate),
            size = 1,
            colour = "white")+
  geom_tile(data = filter(corr_slope_ALL, sig == "Sig."),
            aes(variable, Predict),
            size = 1,
            colour = "black",
            fill = "transparent")+
  geom_text(data = corr_slope_ALL,
            aes(variable, Predict, label = round(estimate, 2),
                fontface = ifelse(sig == "Sig.", "bold", "plain")))+
  scale_fill_gradient2(breaks = seq(-1, 1, 0.2))+
  labs(x = "", y = "", fill = "", p.value = "")+
  theme_minimal()+
  facet_grid(okoregion~year) +
  theme(panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(size = 10)) + labs(fill = "Pearson's\nCorrelation") + 
  theme(text = element_text(size = 16))

ggsave("Figures/Corrplot_ALL.pdf", Figure, width = 14.5, height = 8, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/Corrplot_ALL.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/Corrplot_ALL.jpeg")
```

```{r}
# Mean monthly standardized stream flow. 
# subtract mean and divide by SD. 

Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

flow_daily <- read_csv("Clean_Data/daily_flux_all.csv") %>% 
  dplyr::select(site_id, month, date, year, Q) 

Data <- full_join(Q, Station_Info) %>%  distinct() %>% drop_na() %>% 
  filter(!year %in% c("2017", "2022")) %>% 
  group_by(rapportnavn, date) %>% 
  group_by(rapportnavn, year, month) %>% 
  mutate(Q = mean(Q)) %>%  ungroup() %>% 
  group_by(rapportnavn, year) %>% 
  summarise(group = group, site_id = site_id, okoregion = okoregion,date = date, Q = Q, mean = mean(Q), sd=sd(Q)) %>% 
  mutate(Q = (Q - mean)/sd)

# All stations
Plot <- Data %>% 
  ggplot(aes(x = month(date, label=TRUE, abbr=TRUE), y = Q_sd, group = factor(year(date)), color = factor(year(date)))) + 
  geom_line() +
  geom_point(size = 0.05) +
  #geom_smooth(method = "lm", se = T, size = 0.1) +
  facet_wrap(~rapportnavn, ncol =3) +
  theme_bw() +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) +
  xlab("Month") + labs(color ="year")

ggsave("Figures/standard_flow.pdf", Plot, width = 6, height = 15, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/standard_flow.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/standard_flow.jpeg")


# By group

Plot1 <- Data %>% 
  filter(group == "'18/'20") %>% 
  filter(year %in% c("2018", "2020")) %>% 
  ggplot(aes(x = month(date, label=TRUE, abbr=TRUE), y = Q_sd, group = factor(year(date)), color = factor(year(date)))) + 
  geom_line() +
  geom_point(size = 0.05) +
  scale_color_manual(values=c("#FFCC66", "#264EFF")) +
  #geom_smooth(method = "lm", se = T, size = 0.1) +
  facet_wrap(~rapportnavn, ncol =3) +
  theme_bw() +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) +
  xlab("Month") + labs(color ="year") + xlab(NULL) + ylab("Standardized flow")


Plot2 <- Data %>% 
  filter(group == "'19/'21") %>% 
  filter(year %in% c("2019", "2021")) %>% 
  ggplot(aes(x = month(date, label=TRUE, abbr=TRUE), y = Q_sd, group = factor(year(date)), color = factor(year(date)))) + 
  geom_line() +
  geom_point(size = 0.05) +
  scale_color_manual(values=c("#3399FF", "#FF8000")) +
  #geom_smooth(method = "lm", se = T, size = 0.1) +
  facet_wrap(~rapportnavn, ncol =3) +
  theme_bw() +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) +
  xlab("Month") + labs(color ="year") + xlab(NULL) + ylab("Standardized flow")

Plot3 <- Data %>% 
  filter(group == "'18/'19/'20/'21") %>% 
  ggplot(aes(x = month(date, label=TRUE, abbr=TRUE), y = Q_sd, group = factor(year(date)), color = factor(year(date)))) + 
  geom_line() +
  geom_point(size = 0.05) +
  scale_color_manual(values=c("#FFCC66","#3399FF","#264EFF", "#FF8000")) +
  #geom_smooth(method = "lm", se = T, size = 0.1) +
  facet_wrap(~rapportnavn, ncol =2) +
  theme_bw() +
  theme(axis.text.x = element_text(size =8, angle = 45, hjust = 1)) +
  xlab("Month") + labs(color ="year") + xlab(NULL) + ylab("Standardized flow")


ggsave("Figures/group1_Flow.pdf", Plot1, bg = "white", width = 7, height = 12, device = cairo_pdf)
bitmap <- pdf_render_page("Figures/group1_Flow.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/group1_Flow.jpeg")

ggsave("Figures/group2_Flow.pdf", Plot2, bg = "white", width = 7, height = 12, device = cairo_pdf)
bitmap <- pdf_render_page("Figures/group2_Flow.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/group2_Flow.jpeg")

ggsave("Figures/group3_Flow.pdf", Plot3, bg = "white", width = 5, height = 4, device = cairo_pdf)
bitmap <- pdf_render_page("Figures/group3_Flow.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/group3_Flow.jpeg")
```

# Cluster flow curves

```{r}
##### Cluster flow curves
Data2 <- Data %>% 
  unite("ID", rapportnavn:year, sep = "_", remove = TRUE, na.rm = FALSE) %>% 
  mutate(month = month(date)) %>% 
  dplyr::select(ID, month, Q_sd) %>% distinct()

Data2 <- as.data.frame(Data2)
myClds = cldsLong(Data2)
parKmlShape(aggregationMethod="hierarchical")
kmlShape(myClds, nbClusters = 3, timeScale = 0.1, 
         FrechetSumOrMax ="max", toPlot="both", parAlgo=parKmlShape())

clusters <- as.data.frame(myClds["clusters"])

par(ask=FALSE)
plot(myClds)


### five clusters
Data2 <- Data %>% 
  unite("ID", rapportnavn:year, sep = "_", remove = TRUE, na.rm = FALSE) %>% 
  mutate(month = month(date)) %>% 
  dplyr::select(ID, month, Q_sd) %>% distinct()

Data2 <- as.data.frame(Data2)
myClds = cldsLong(Data2)
parKmlShape(aggregationMethod="hierarchical")
kmlShape(myClds, nbClusters = 5, timeScale = 0.1, 
         FrechetSumOrMax ="max", toPlot="both", parAlgo=parKmlShape())

clusters2 <- as.data.frame(myClds["clusters"]) %>% 
  mutate(cluster = myClds["clusters"]) %>% 
  mutate(ID = row.names(.))

par(ask=FALSE)

plot(myClds)

#Clusters <- clusters2 %>% 
#  mutate(cluster =ifelse(grepl("3|4", myClds["clusters"]), 3, myClds["clusters"])) %>% 
#  mutate(cluster =ifelse(grepl("5", myClds["clusters"]), 4, cluster)) %>% 
#  mutate(ID = row.names(.))

Data3 <- Data %>% 
  unite("ID", rapportnavn:year, sep = "_", remove = F, na.rm = FALSE) 
Data4 <- full_join(Data3, clusters2)

Plot <- Data4 %>% 
  ggplot(aes(x = month(date, label=TRUE, abbr=TRUE), y = Q_sd)) + 
  geom_line(aes(group = factor(ID), color = factor(cluster)), size = 0.9, alpha = 0.5) +
  geom_point(aes(group = factor(ID), color = factor(cluster)), size = 0.03, alpha = 0.6) +
  stat_summary(aes(group = cluster), fun.y=mean, colour="black", geom="line", size = 1.4) +
  facet_wrap(~cluster, ncol = 1) +
  xlab("Month") + ylab("standardized flow") + labs(color ="year") +
  theme_classic() +
  scale_color_brewer(palette="Set1") +
  theme(axis.text.x = element_text(size =6, angle = 45, hjust = 1)) + 
  theme(text = element_text(size = 8))  +
  theme(legend.position = "none")

ggsave("Figures/standard_flow_cluster1.pdf", Plot, width = 3, height = 8, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/standard_flow_cluster1.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/standard_flow_cluster1.jpeg")
```

# FLow curves all years

```{r}

# Prep data 
Station_Info <- read_csv("Clean_Data/Station_Info.csv") %>% 
  dplyr::select(site_id, rapportnavn, okoregion, group) 

flow_daily <- read_csv("Clean_Data/Intermediate/Hydrology_Data_daily_ALLYEARS.csv") %>% 
  dplyr::select(site_id, month, datetime, year, Q = value_mean) 

Data <- full_join(flow_daily, Station_Info) %>%  distinct() %>% drop_na() %>% 
  #filter(!year %in% c("2017", "2022")) %>% 
 # group_by(rapportnavn, datetime) %>% 
  #mutate(Q = Q * 86400) %>% ungroup() %>% 
  group_by(rapportnavn, month) %>% 
  mutate(Q = mean(Q)) %>%  ungroup() %>% 
  group_by(rapportnavn) %>% 
  summarise(group = group, site_id = site_id, okoregion = okoregion,date = datetime, Q = Q, mean = mean(Q), sd=sd(Q)) %>% 
  mutate(Q_sd = (Q - mean)/sd) %>%
  mutate(month = month(date)) %>% 
  dplyr::select(-c(date)) %>% distinct()

##### Cluster flow curves
Data2 <- Data %>% 
  #unite("ID", rapportnavn:year, sep = "_", remove = TRUE, na.rm = FALSE) %>% 
  #mutate(month = month(date)) %>% 
  dplyr::select(rapportnavn, month, Q_sd) %>% distinct()

#Data2 <- as.data.frame(Data2)
#myClds = cldsLong(Data2)
#parKmlShape(aggregationMethod="hierarchical")
#kmlShape(myClds, nbClusters = 3, timeScale = 0.1, 
       #  FrechetSumOrMax ="max", toPlot="both", parAlgo=parKmlShape())

#clusters <- as.data.frame(myClds["clusters"])

#par(ask=FALSE)
#plot(myClds)

set.seed(123)
### five clusters
#Data2 <- Data %>% 
#  unite("ID", rapportnavn:year, sep = "_", remove #= TRUE, na.rm = FALSE) %>% 
#  mutate(month = month(date)) %>% 
#  dplyr::select(ID, month, Q_sd) %>% distinct()

Data2 <- as.data.frame(Data2)
myClds = cldsLong(Data2)
parKmlShape(aggregationMethod="hierarchical")
kmlShape(myClds, nbClusters = 5, timeScale = 0.1, 
         FrechetSumOrMax ="max", toPlot="both", parAlgo=parKmlShape())

clusters2 <- as.data.frame(myClds["clusters"]) %>% 
  mutate(cluster = myClds["clusters"]) %>% 
  mutate(rapportnavn = row.names(.))

par(ask=FALSE)

plot(myClds)

#Clusters <- clusters2 %>% 
#  mutate(cluster =ifelse(grepl("3|4", myClds["clusters"]), 3, myClds["clusters"])) %>% 
#  mutate(cluster =ifelse(grepl("5", myClds["clusters"]), 4, cluster)) %>% 
#  mutate(ID = row.names(.))


Data3 <- Data %>% dplyr::select(c(rapportnavn, month, Q_sd))
  
#unite("ID", rapportnavn:year, sep = "_", remove = F, na.rm = FALSE) 
Data4 <- full_join(Data3, clusters2)

Plot <- Data4 %>% 
  ggplot(aes(x = month(month, label = T), y = Q_sd)) + 
  geom_line(aes(group = factor(rapportnavn), color = factor(cluster)), size = 0.9, alpha = 0.5) +
  geom_point(aes(group = factor(rapportnavn), color = factor(cluster)), size = 0.03, alpha = 0.6) +
  stat_summary(aes(group = cluster), fun.y=mean, colour="black", geom="line", size = 1.4) +
  facet_wrap(~cluster, ncol = 1) +
  xlab("Month") + ylab("standardized flow") + labs(color ="year") +
  theme_classic() +
  scale_color_brewer(palette="Set1") +
  theme(axis.text.x = element_text(size =6, angle = 45, hjust = 1)) + 
  theme(text = element_text(size = 8))  +
  theme(legend.position = "none")

ggsave("Figures/standard_flow_cluster_allyears.pdf", Plot, width = 3, height = 8, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/standard_flow_cluster_allyears.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/standard_flow_cluster_allyears.jpeg")
```

```{r}

```

# Flow curves clusted + Map

```{r}
# river station coordinates
Station_Info <- read_csv("Clean_Data/Station_Info.csv") 

X <- full_join(Station_Info, Data4) %>% 
  dplyr::select(c(site_id, latitude, longitude, cluster)) %>% distinct() %>% drop_na()


stations_cord <- st_as_sf(X, coords = c("longitude", "latitude"), crs = "WGS84", remove = FALSE) 
stations_cord = st_transform(stations_cord, "EPSG:25833")

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

map <- ggplot(data = world) +
  geom_sf() +
  coord_sf(xlim = c(3.1611, 32.000), ylim = c(57.000, 72.000), expand = FALSE) +
  layer_spatial(stations_cord, aes(col = factor(cluster)), xlim = c(0.0611, 32.000), ylim = c(57.000, 72.000)) +
  coord_sf(xlim = c(3.1611, 32.000), ylim = c(57.000, 72.000), expand = FALSE) +
  theme_classic() +
  scale_color_brewer(palette="Set1") +
  theme(legend.position = "bottom") + labs(color ="flow regime")

ggsave("Figures/map_clusters.pdf", map, width = 4, height = 5, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/map_clusters.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/map_clusters.jpeg")


p <- (map|Plot) + plot_layout(ncol=2,widths=c(2.3,0.7), heights =c(1,1))

ggsave("Figures/map_clusters2.pdf", p, bg = "white", device = cairo_pdf)
bitmap <- pdf_render_page("Figures/map_clusters2.pdf", page = 1, dpi = 300)
jpeg::writeJPEG(bitmap, "Figures/map_clusters2.jpeg")
```

# Seasonal standardized flux + totall annual flux

```{r}

```
